### ISSUE TITLE
Error when running example data

### ISSUE THREAD

**Issue by EthanKhew** [JingHuangLab/topoLink#1]
Hi. I have installed topoLink as recommended in the github page but when faced an error when running the example line. The error are returned as below. Hope you could help assist with the matter. 

``python topo_links.py -in ./examples/glnB-gspJ.pdb``

``@> 1196 atoms and 1 coordinate set(s) were parsed in 0.01s.``
``Traceback (most recent call last):``
``  File "topo_links.py", line 318, in <module>
    scanbegin=scanbegin, threshscore=threshscore, discutoff=discutoff, ter_rm=ter_rm)``
``  File "topo_links.py", line 272, in topo_link
    scanend=scanend, detail=detail, outpath=outpath, ter_rm=ter_rm)``
``  File "topo_links.py", line 213, in tln_2chains
    dict_l1, threshscore, scanbegin, scanend)``
``  File "topo_links.py", line 122, in identify_pierce_atoms
    gln2matrix=np.array(gln2.get('matrix'))``
``AttributeError: 'list' object has no attribute 'get'``

**Comment by yingnan-hou** [comment]
This error could be due to using a version of _topoly_ that is higher than 1.0.0, where the output format of the gln function has been changed. It is recommended to use _topoly_ version between v0.9.24 and v1.0.0.

If you have any further inquiries or concerns, please feel free to provide feedback. We are here to assist you. Thank you.

**Comment by EthanKhew** [comment]
Hi @yingnan-hou . Apologies for the late feedback as I was trying to understand the output summary file. 
Indeed topoly version was the issue and changing to the lower version have solved the issue. 

I am a bit confused with the output of the summary text file. I can't seem to find the definitive columns as mentioned in the main page. Could you help direct me to which column is to which. For this run, I kept all parameters as default. One of the output are as below. 
`./batchtest_input//operon_17919_relaxed_rank_001_alphafold2_multimer_v3_model_2_seed_000.pdb AB 0 {'tln': 0, 'wholegln': -0.001, 'chain_A': 0, 'chain_B': 0, 'resid_chain_A': '', 'resid_chain_B': '', 'res_breaks': 0, 'maxgln_A': -0.124, 'maxgln_B': -0.232, 'maxtln_A': 0, 'maxtln_B': 0, 'minres': 24}`

I also tried running with "`detail`" parameter which created additional files. Could you please advise on how to interpret the `glnmap.png`, `matrix.npy` , and `interselected.pdb` files. I have shared them in the zip folder below. 
From my understanding using ChimeraX, I viewed the `interselected.pdb` file (beige) with my operon complex file (blue) and there doesn't seem to be any TopoLinks present. I would like to run the program on 1000+ protein multimer files and would like to know if I could get a quick overview on which multimer complex has topolink present/absent with the mentioned summary file. Thanks in advance. 
![image](https://github.com/JingHuangLab/topoLink/assets/89140255/19fa5b7b-d540-48f5-8f4d-dfcfbb73b383)
[topolink_operon17919.zip](https://github.com/JingHuangLab/topoLink/files/14987549/topolink_operon17919.zip)

**Comment by yingnan-hou** [comment]
I apologize for the confusion. The column names were not marked in the summary file because  the analysis results will be continuously added into the summary file. 

Let's take your example to interpret the results: `./batchtest_input//operon_17919_relaxed_rank_001_alphafold2_multimer_v3_model_2_seed_000.pdb` is the first column (the file of the structure); `AB` is the second column (the paired chains of the structure, i,e., chain A and chain B); `0` is the third column (the number of topological links between chain A and chain B); Others is the fourth column (Detailed information stored in python dictionary format. For detailed explanation, please refer to the subsequent updated README.md). **By checking whether the value in the third column is greater than 0, you can quickly determine whether there is a topological link between the two corresponding chains.** There are no topological links in your example as well as in the three proteins in your zip data. By the way, the example we provided (`./examples/glnB-gspJ.pdb`) is a protein containing a topological link.

To interpret the `AB-glnmap-A.png` in the zip folder,  "AB" in the file name means that the paired chains are chain A and chain B; "-A" in the file name means that this glnmap is for chain A. For this figure, each point of the heatmap represents a fragment of chain A, specifically for the chain A at the interface in `inter_selected_AB.pdb` (the row represents the starting atom index, and the column represents the ending atom index). The color represents the GLN value between this fragment and chain B (at the interface in `inter_selected_AB.pdb`). The larger the absolute value, the more intense the degree of entanglement. By default, when the absolute value is greater than 0.8, the corresponding fragment will be judged to have a topological link. The `AB-matrix-A.npy` file stores the GLN value corresponding to the figure `AB-glnmap-A.png`.

Note that if you analyze a protein complex with more than two chains, all pairwise combinations of these chains will be analyzed.

Hope these can be helpful to you. Please feel free to contact us if you have any other questions. Thank you!

**Comment by EthanKhew** [comment]
Thank you very much for the detailed explanation @yingnan-hou . Since the "columns" were to closed together with the name file, I missed it. Thanks for the clarification as well and hope this post will help other users in the future.
